---
name: "Download Monitor"
guid: "4344669f-555b-4525-b86f-d66dbb9ae81b"
version: "0.2.1.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Monitor and display Radarr download progress in Jellyfin"
description: >
  A Jellyfin plugin that adds a Downloads menu item to the sidebar,
  allowing you to monitor active downloads from Radarr directly
  within the Jellyfin web interface.
category: "General"
owner: "Kyandro"
artifacts:
- "Jellyfin.Plugin.DownloadMonitor.dll"
changelog: >
  Initial release
